FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IHYydgpkZXNjcmlwdGlvbjogSW1wb3J0IGEgdmlydHVhbCBtYWNo\
aW5lIGZyb20gVm13YXJlIGZvciBLdWJldmlydCB1c2luZyB2aXJ0LXYydgpiaW5kYWJsZTogRmFs\
c2UKYXN5bmM6IG9wdGlvbmFsCm1ldGFkYXRhOgogIGRpc3BsYXlOYW1lOiBJbXBvcnQgYSB2bSBm\
cm9tIHZtd2FyZSB1c2luZyB2aXJ0LXYydiAoQVBCKQogIGltYWdlVXJsOiBodHRwczovL2Nkbi5w\
YnJkLmNvL2ltYWdlcy9INUd1dGQ3LnBuZwpwbGFuczoKICAtIG5hbWU6IGRlZmF1bHQKICAgIGRl\
c2NyaXB0aW9uOiBSZXRyaWV2ZSBWTSBmcm9tIHZtd2FyZQogICAgZnJlZTogVHJ1ZQogICAgbWV0\
YWRhdGE6IHt9CiAgICBwYXJhbWV0ZXJzOgogICAgICAtIHRpdGxlOiBWbXdhcmUgdXJsIHRvIGVz\
eGkKICAgICAgICBuYW1lOiB1cmwKICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICByZXF1aXJl\
ZDogdHJ1ZQogICAgICAtIHRpdGxlOiBWaXJ0dWFsIG1hY2hpbmUgbmFtZQogICAgICAgIG5hbWU6\
IHZtX25hbWUKICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICByZXF1aXJlZDogdHJ1ZQogICAg\
ICAtIHRpdGxlOiBWbXdhcmUgQWRtaW4KICAgICAgICBuYW1lOiB1c2VybmFtZQogICAgICAgIHR5\
cGU6IHN0cmluZwogICAgICAgIHJlcXVpcmVkOiB0cnVlCiAgICAgICAgZGlzcGxheV90eXBlOiB1\
c2VybmFtZQogICAgICAtIHRpdGxlOiBWbXdhcmUgQWRtaW4gUGFzc3dvcmQKICAgICAgICBuYW1l\
OiBwYXNzd29yZAogICAgICAgIHR5cGU6IHN0cmluZwogICAgICAgIHJlcXVpcmVkOiB0cnVlCiAg\
ICAgICAgZGlzcGxheV90eXBlOiBwYXNzd29yZAo="

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
RUN yum -y install libvirt-client curl qemu-img && yum clean all
USER apb
